spring:
  application:
    name: studentProject
  data:
    mongodb:
      uri: mongodb://localhost:27017/student
      database: student
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8089


